export let sampleData = [
  {
    Id: "G001",
    Name: "Grand Theft Auto V",
    Price: 6000,
    img: "gimg/gtav.jpg",
    Status: "in stock",
  },
  {
    Id: "G002",
    Name: "Cities Skyline",
    Price: 4600,
    img: "gimg/ctsl.jpg",
    Status: "In stock",
  },
  {
    Id: "G003",
    Name: "Fall Guys: Ultimate Knockout",
    Price: 6000,
    img: "gimg/fg.jpg",
    Status: "In stock",
  },
  {
    Id: "G004",
    Name: "Home Sweet Home",
    Price: 6000,
    img: "gimg/hsh.jpg",
    Status: "In stock",
  },
  {
    Id: "G005",
    Name: "Minecraft",
    Price: 9900,
    img: "gimg/minecraft.jpg",
    Status: "In stock",
  },
  {
    Id: "G007",
    Name: "OverWatch",
    Price: 6000,
    img: "gimg/overwatch.jpg",
    Status: "Out of stock",
  },
  {
    Id: "G008",
    Name: "PlayerUnknown's Battlegrounds",
    Price: 6000,
    img: "gimg/pubg.jpg",
    Status: "In stock",
  },
  {
    Id: "G009",
    Name: "Plants vs Zombies",
    Price: 4200,
    img: "gimg/pvz.jpg",
    Status: "In stock",
  },
  {
    Id: "G010",
    Name: "The sims 4",
    Price: 6000,
    img: "gimg/thesim4.jpg",
    Status: "In stock",
  }
];
